name: "Nix"
on:
    pull_request:
    push:
jobs:
    tests:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: cachix/install-nix-action@v31
            - run: nix build
